"""
IDPDR — Master Drug Database (v1.0)
======================================
Consolidated, uniform-schema drug knowledge base. This module merges what used
to be two disconnected data sources (`views.DRUG_DATABASE`, a 10-drug dict, and
the unused `drug_data.DRUG_KNOWLEDGE`, a 12-drug dict) and extends coverage to
EVERY drug that appears in the trained recommendation model / review dataset
(`models_pkl/recommendations.json`, `data/drug_reviews.csv`) — 57 drugs total.

Every entry follows the same flat schema so the Drug Search and Drug Report
modules never return a blank/partial profile:

    generic_name, brand_names, drug_class, description, uses, dosage,
    side_effects, contraindications, drug_interactions, food_interactions,
    pregnancy, breastfeeding, kidney_warning, liver_warning, storage,
    overdose, missed_dose, alternatives, price_inr, prescription_required,
    manufacturer, availability, condition

All information is general, educational patient-reference information (the
same level of detail as a standard patient information leaflet) and is not a
substitute for professional medical advice.
"""

# ─────────────────────────────────────────────────────────────────
# Fully curated entries (originally in views.py + drug_data.py,
# merged and de-duplicated)
# ─────────────────────────────────────────────────────────────────
_CURATED = {
    "Metformin": {
        "generic_name": "Metformin Hydrochloride",
        "brand_names": ["Glucophage", "Glumetza", "Fortamet", "Glycomet"],
        "drug_class": "Biguanide Antidiabetic",
        "description": "Metformin is the first-line oral antidiabetic drug for type 2 diabetes. It works by decreasing hepatic glucose production and improving insulin sensitivity.",
        "uses": ["Type 2 Diabetes", "Prediabetes", "PCOS", "Weight management"],
        "dosage": {"adult": "500–2000 mg/day in divided doses", "max": "2550 mg/day", "renal": "Adjust based on eGFR"},
        "side_effects": ["Nausea", "Diarrhea", "Stomach upset", "Metallic taste", "Lactic acidosis (rare)"],
        "contraindications": ["Severe renal impairment (eGFR <30)", "Metabolic acidosis", "Radiographic contrast use"],
        "drug_interactions": ["Alcohol", "Contrast dye", "Topiramate", "Furosemide"],
        "food_interactions": ["Take with food to reduce GI side effects", "Avoid excessive alcohol"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Compatible with breastfeeding",
        "kidney_warning": "Contraindicated if eGFR < 30 mL/min. Use caution if eGFR 30-45.",
        "liver_warning": "Avoid in hepatic impairment due to lactic acidosis risk",
        "storage": "Store at room temperature 20-25°C, away from moisture",
        "overdose": "Contact poison control. May cause lactic acidosis. Hemodialysis may help.",
        "missed_dose": "Take as soon as remembered. Skip if almost time for next dose.",
        "alternatives": ["Glipizide", "Sitagliptin", "Empagliflozin", "Liraglutide"],
        "price_inr": "₹20–80 per strip (30 tablets)",
        "prescription_required": True,
        "manufacturer": "Various (generic widely available)",
        "availability": "Widely available",
        "condition": "Diabetes Type 2",
    },
    "Ozempic": {
        "generic_name": "Semaglutide",
        "brand_names": ["Ozempic", "Wegovy", "Rybelsus"],
        "drug_class": "GLP-1 Receptor Agonist",
        "description": "Semaglutide is a glucagon-like peptide-1 (GLP-1) receptor agonist that stimulates insulin secretion and reduces appetite.",
        "uses": ["Type 2 Diabetes", "Obesity management", "Cardiovascular risk reduction"],
        "dosage": {"adult": "0.25mg weekly (starting), up to 2mg weekly", "max": "2mg/week", "renal": "No dose adjustment needed"},
        "side_effects": ["Nausea", "Vomiting", "Diarrhea", "Constipation", "Injection site reactions"],
        "contraindications": ["Personal/family history of MTC", "MEN 2", "Pregnancy"],
        "drug_interactions": ["Oral medications (delayed absorption)", "Warfarin (monitor INR)"],
        "food_interactions": ["Take at any time, with or without food"],
        "pregnancy": "Category C - Not recommended during pregnancy",
        "breastfeeding": "Not recommended",
        "kidney_warning": "No dose adjustment needed for mild-moderate renal impairment",
        "liver_warning": "Limited data in severe hepatic impairment",
        "storage": "Refrigerate unused pens at 2-8°C. In use: room temperature up to 56 days.",
        "overdose": "Contact emergency services. Monitor blood glucose.",
        "missed_dose": "If within 5 days, take as soon as possible. Otherwise skip.",
        "alternatives": ["Dulaglutide", "Liraglutide", "Exenatide", "Metformin"],
        "price_inr": "₹5,000–8,000 per pen",
        "prescription_required": True,
        "manufacturer": "Novo Nordisk",
        "availability": "Available at major pharmacies",
        "condition": "Diabetes Type 2",
    },
    "Lisinopril": {
        "generic_name": "Lisinopril",
        "brand_names": ["Zestril", "Prinivil", "Qbrelis"],
        "drug_class": "ACE Inhibitor",
        "description": "Lisinopril is an angiotensin-converting enzyme (ACE) inhibitor used to treat high blood pressure and heart failure.",
        "uses": ["Hypertension", "Heart failure", "Post-MI", "Diabetic nephropathy"],
        "dosage": {"adult": "10–40 mg once daily", "max": "80 mg/day", "renal": "Reduce dose if eGFR < 30"},
        "side_effects": ["Dry cough", "Dizziness", "Hyperkalemia", "Hypotension", "Angioedema (rare)"],
        "contraindications": ["History of angioedema", "Bilateral renal artery stenosis", "Pregnancy"],
        "drug_interactions": ["NSAIDs", "Potassium-sparing diuretics", "Lithium", "ARBs"],
        "food_interactions": ["Avoid high-potassium foods", "Avoid salt substitutes"],
        "pregnancy": "Category D - Contraindicated in 2nd/3rd trimester",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Monitor renal function. May cause acute kidney injury in certain conditions.",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store below 25°C, protect from moisture",
        "overdose": "Contact poison control. Monitor blood pressure and kidney function.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Amlodipine", "Enalapril", "Losartan", "Valsartan"],
        "price_inr": "₹30–100 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Widely available",
        "condition": "Hypertension",
    },
    "Sertraline": {
        "generic_name": "Sertraline Hydrochloride",
        "brand_names": ["Zoloft", "Serlift", "Daxid"],
        "drug_class": "SSRI (Selective Serotonin Reuptake Inhibitor)",
        "description": "Sertraline is an SSRI antidepressant that increases serotonin levels in the brain, improving mood and reducing anxiety.",
        "uses": ["Major Depressive Disorder", "OCD", "Panic Disorder", "PTSD", "Social Anxiety"],
        "dosage": {"adult": "50–200 mg/day", "starting": "25–50 mg/day", "max": "200 mg/day"},
        "side_effects": ["Nausea", "Insomnia", "Diarrhea", "Dry mouth", "Sexual dysfunction", "Sweating"],
        "contraindications": ["MAO inhibitors", "Pimozide", "Linezolid"],
        "drug_interactions": ["MAOIs", "Warfarin", "Lithium", "Tramadol", "Triptans"],
        "food_interactions": ["Can be taken with or without food", "Avoid alcohol"],
        "pregnancy": "Category C - Weigh risk/benefit",
        "breastfeeding": "Compatible (low levels in breast milk)",
        "kidney_warning": "No adjustment needed for mild-moderate renal impairment",
        "liver_warning": "Use lower doses in hepatic impairment",
        "storage": "Store at room temperature, away from moisture",
        "overdose": "Seek emergency care. Serotonin syndrome risk.",
        "missed_dose": "Take as soon as remembered unless near next dose time.",
        "alternatives": ["Fluoxetine", "Escitalopram", "Venlafaxine", "Mirtazapine"],
        "price_inr": "₹40–150 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Available at pharmacies",
        "condition": "Depression",
    },
    "Salbutamol": {
        "generic_name": "Salbutamol (Albuterol)",
        "brand_names": ["Ventolin", "Proventil", "Asthalin"],
        "drug_class": "Short-Acting Beta-2 Agonist (SABA)",
        "description": "Salbutamol is a fast-acting bronchodilator that relieves asthma attacks and bronchospasm by relaxing airway muscles.",
        "uses": ["Asthma (acute relief)", "COPD", "Exercise-induced bronchospasm"],
        "dosage": {"adult": "100–200 mcg (1-2 puffs) as needed", "max": "800 mcg/day", "nebulizer": "2.5–5 mg every 4-6 hours"},
        "side_effects": ["Tremors", "Palpitations", "Tachycardia", "Headache", "Hypokalemia"],
        "contraindications": ["Hypersensitivity to salbutamol"],
        "drug_interactions": ["Beta-blockers", "MAOIs", "Tricyclic antidepressants", "Diuretics"],
        "food_interactions": ["None significant"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Compatible",
        "kidney_warning": "No adjustment needed",
        "liver_warning": "No adjustment needed",
        "storage": "Store at room temperature. Protect inhaler from heat and direct sunlight.",
        "overdose": "Seek emergency care. Monitor heart rate and potassium.",
        "missed_dose": "Use only as needed for symptom relief",
        "alternatives": ["Terbutaline", "Levosalbutamol", "Formoterol (long-acting)"],
        "price_inr": "₹60–150 per inhaler",
        "prescription_required": True,
        "manufacturer": "Various (GSK, Cipla)",
        "availability": "Widely available",
        "condition": "Asthma",
    },
    "Sumatriptan": {
        "generic_name": "Sumatriptan Succinate",
        "brand_names": ["Imitrex", "Imigran", "Suminat"],
        "drug_class": "Triptan (5-HT1 Agonist)",
        "description": "Sumatriptan is a selective serotonin receptor agonist used to treat acute migraine attacks by constricting blood vessels.",
        "uses": ["Acute Migraine", "Cluster Headaches"],
        "dosage": {"oral": "50–100 mg per attack", "nasal": "5–20 mg", "injection": "6 mg SC", "max": "200 mg/24 hrs"},
        "side_effects": ["Injection site pain", "Tingling", "Flushing", "Chest tightness", "Drowsiness"],
        "contraindications": ["Ischemic heart disease", "Uncontrolled hypertension", "MAOIs"],
        "drug_interactions": ["MAOIs", "SSRIs (serotonin syndrome risk)", "Ergotamine"],
        "food_interactions": ["Can be taken with food"],
        "pregnancy": "Category C",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution in severe renal impairment",
        "liver_warning": "Contraindicated in severe hepatic impairment",
        "storage": "Store below 30°C",
        "overdose": "Seek emergency care. Monitor cardiovascular function.",
        "missed_dose": "Take at onset of migraine. Do not take preventively.",
        "alternatives": ["Rizatriptan", "Naratriptan", "Ibuprofen", "Ergotamine"],
        "price_inr": "₹200–600 per pack",
        "prescription_required": True,
        "manufacturer": "Various (GSK, Sun Pharma)",
        "availability": "Available at pharmacies",
        "condition": "Migraine",
    },
    "Omeprazole": {
        "generic_name": "Omeprazole",
        "brand_names": ["Prilosec", "Losec", "Omez"],
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "description": "Omeprazole reduces stomach acid production by irreversibly blocking the proton pump in gastric parietal cells.",
        "uses": ["GERD", "Peptic ulcers", "H. pylori eradication", "Zollinger-Ellison syndrome"],
        "dosage": {"adult": "20–40 mg once daily", "max": "120 mg/day for ZE syndrome"},
        "side_effects": ["Headache", "Nausea", "Diarrhea", "Hypomagnesemia (long-term)", "C. diff risk"],
        "contraindications": ["Rilpivirine (HIV)", "Hypersensitivity to PPIs"],
        "drug_interactions": ["Clopidogrel", "Methotrexate", "Warfarin", "Digoxin"],
        "food_interactions": ["Take 30 minutes before meals"],
        "pregnancy": "Category C",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Reduce dose in severe hepatic impairment",
        "storage": "Store below 25°C in original packaging",
        "overdose": "Generally low toxicity. Supportive care.",
        "missed_dose": "Take as soon as remembered before the next meal.",
        "alternatives": ["Pantoprazole", "Esomeprazole", "Rabeprazole", "Ranitidine"],
        "price_inr": "₹30–80 per strip",
        "prescription_required": False,
        "manufacturer": "Various",
        "availability": "Widely available (OTC in some countries)",
        "condition": "GERD",
    },
    "Levothyroxine": {
        "generic_name": "Levothyroxine Sodium",
        "brand_names": ["Synthroid", "Eltroxin", "Thyronorm"],
        "drug_class": "Thyroid Hormone Replacement",
        "description": "Levothyroxine is a synthetic form of thyroxine (T4) used to replace or supplement thyroid hormone in hypothyroidism.",
        "uses": ["Hypothyroidism", "Thyroid cancer (suppression)", "Goiter"],
        "dosage": {"adult": "1.6 mcg/kg/day (usual)", "starting": "25–50 mcg/day", "max": "300 mcg/day"},
        "side_effects": ["Palpitations", "Anxiety", "Weight loss (excess dose)", "Insomnia", "Heat intolerance"],
        "contraindications": ["Untreated adrenal insufficiency", "Thyrotoxicosis"],
        "drug_interactions": ["Calcium carbonate", "Iron supplements", "Warfarin", "PPIs"],
        "food_interactions": ["Take on empty stomach 30-60 mins before breakfast", "Coffee may reduce absorption"],
        "pregnancy": "Category A - Safe in pregnancy (dose may need adjustment)",
        "breastfeeding": "Compatible",
        "kidney_warning": "No specific adjustment",
        "liver_warning": "Absorbed primarily in small intestine; liver disease minimal effect",
        "storage": "Store below 25°C, protect from light and moisture",
        "overdose": "Seek emergency care. Thyrotoxic crisis possible.",
        "missed_dose": "Take as soon as remembered, unless almost time for next dose.",
        "alternatives": ["Liothyronine (T3)", "Desiccated thyroid"],
        "price_inr": "₹30–80 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Available at pharmacies",
        "condition": "Hypothyroidism",
    },
    "Atorvastatin": {
        "generic_name": "Atorvastatin Calcium",
        "brand_names": ["Lipitor", "Atorva", "Tonact"],
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "description": "Atorvastatin reduces cholesterol production in the liver by inhibiting HMG-CoA reductase, lowering LDL and triglycerides.",
        "uses": ["High Cholesterol", "Cardiovascular prevention", "Familial hypercholesterolemia"],
        "dosage": {"adult": "10–80 mg once daily", "max": "80 mg/day"},
        "side_effects": ["Myalgia", "Liver enzyme elevation", "Rhabdomyolysis (rare)", "GI upset"],
        "contraindications": ["Active liver disease", "Pregnancy", "Breastfeeding"],
        "drug_interactions": ["Cyclosporine", "Macrolide antibiotics", "Azole antifungals", "Gemfibrozil"],
        "food_interactions": ["Avoid grapefruit juice (increases drug levels)", "Can be taken with or without food"],
        "pregnancy": "Category X - Contraindicated",
        "breastfeeding": "Contraindicated",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Contraindicated in active liver disease. Monitor LFTs.",
        "storage": "Store below 25°C",
        "overdose": "Contact poison control. No specific antidote.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Rosuvastatin", "Simvastatin", "Pravastatin", "Pitavastatin"],
        "price_inr": "₹40–120 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Widely available",
        "condition": "High Cholesterol",
    },
    "Amoxicillin": {
        "generic_name": "Amoxicillin Trihydrate",
        "brand_names": ["Amoxil", "Trimox", "Novamox"],
        "drug_class": "Aminopenicillin Antibiotic",
        "description": "Amoxicillin is a broad-spectrum penicillin antibiotic that kills bacteria by inhibiting cell wall synthesis.",
        "uses": ["Bacterial infections", "Respiratory tract infections", "UTIs", "H. pylori", "Ear infections"],
        "dosage": {"adult": "250–500 mg every 8 hours or 500–875 mg twice daily", "max": "3g/day"},
        "side_effects": ["Nausea", "Diarrhea", "Skin rash", "Allergic reactions", "Yeast infections"],
        "contraindications": ["Penicillin allergy", "Mononucleosis (causes rash)"],
        "drug_interactions": ["Warfarin", "Methotrexate", "Probenecid", "Oral contraceptives"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally safe",
        "breastfeeding": "Compatible",
        "kidney_warning": "Reduce dose/increase interval if eGFR < 30",
        "liver_warning": "Use with caution in severe hepatic impairment",
        "storage": "Capsules: room temperature. Suspension: refrigerate, use within 14 days.",
        "overdose": "Supportive care. Crystalluria may occur.",
        "missed_dose": "Take as soon as remembered. Complete the full course.",
        "alternatives": ["Azithromycin", "Clarithromycin", "Doxycycline", "Ciprofloxacin"],
        "price_inr": "₹20–60 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Widely available",
        "condition": "Infection",
    },
    "Lorazepam": {
        "generic_name": "Lorazepam",
        "brand_names": ["Ativan", "Loraz", "Temesta"],
        "drug_class": "Benzodiazepine / Anxiolytic",
        "description": "Lorazepam is a benzodiazepine that enhances the activity of GABA, a calming neurotransmitter, used for anxiety, insomnia, and seizures.",
        "uses": ["Anxiety disorders", "Panic disorder", "Insomnia (short-term)", "Seizure prevention", "Pre-operative sedation"],
        "dosage": {"adult": "0.5–2 mg orally 2–3 times daily", "elderly": "0.5–1 mg once or twice daily", "max": "10 mg/day"},
        "side_effects": ["Drowsiness", "Dizziness", "Weakness", "Unsteadiness", "Memory problems"],
        "contraindications": ["Acute narrow-angle glaucoma", "Severe respiratory insufficiency", "Sleep apnea"],
        "drug_interactions": ["Opioids (respiratory depression)", "Alcohol", "Other CNS depressants", "Valproic acid"],
        "food_interactions": ["Avoid alcohol", "Grapefruit may increase levels"],
        "pregnancy": "Category D - Evidence of fetal risk",
        "breastfeeding": "Use with caution; excreted in breast milk",
        "kidney_warning": "Use with caution in renal impairment",
        "liver_warning": "Use with caution; may accumulate in hepatic impairment",
        "storage": "Store at room temperature 15-30°C, away from moisture and heat",
        "overdose": "Seek emergency care. Flumazenil is the antidote.",
        "missed_dose": "Take as soon as remembered. Never double dose.",
        "alternatives": ["Alprazolam", "Diazepam", "Clonazepam", "Buspirone (non-benzodiazepine)"],
        "price_inr": "₹15–80 per tablet",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Prescription required; Schedule IV controlled substance",
        "condition": "Anxiety",
    },
    "Amlodipine": {
        "generic_name": "Amlodipine Besylate",
        "brand_names": ["Norvasc", "Amlodac", "Amlong"],
        "drug_class": "Calcium Channel Blocker (Dihydropyridine)",
        "description": "Amlodipine relaxes and widens blood vessels by blocking calcium entry into vascular smooth muscle, lowering blood pressure.",
        "uses": ["Hypertension", "Chronic stable angina", "Coronary artery disease"],
        "dosage": {"adult": "5–10 mg once daily", "starting": "5 mg once daily", "max": "10 mg/day"},
        "side_effects": ["Ankle/leg swelling", "Flushing", "Dizziness", "Headache", "Fatigue"],
        "contraindications": ["Severe hypotension", "Cardiogenic shock", "Severe aortic stenosis"],
        "drug_interactions": ["Simvastatin (dose limit)", "CYP3A4 inhibitors", "Other antihypertensives"],
        "food_interactions": ["Avoid grapefruit juice"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No dose adjustment usually needed",
        "liver_warning": "Start at lower dose in hepatic impairment",
        "storage": "Store at room temperature, protect from moisture",
        "overdose": "Seek emergency care. Monitor blood pressure and heart rate.",
        "missed_dose": "Take as soon as remembered. Skip if near next dose.",
        "alternatives": ["Lisinopril", "Losartan", "Nifedipine", "Metoprolol"],
        "price_inr": "₹20–70 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Widely available",
        "condition": "Hypertension",
    },
    "Zolpidem": {
        "generic_name": "Zolpidem Tartrate",
        "brand_names": ["Ambien", "Stilnox", "Zolfresh"],
        "drug_class": "Non-Benzodiazepine Sedative-Hypnotic (Z-drug)",
        "description": "Zolpidem is a short-acting sedative-hypnotic that binds GABA-A receptors to promote sleep onset for short-term insomnia treatment.",
        "uses": ["Short-term insomnia (difficulty falling asleep)"],
        "dosage": {"adult": "5–10 mg immediately before bedtime", "elderly": "5 mg", "max": "10 mg/day"},
        "side_effects": ["Drowsiness", "Dizziness", "Headache", "Sleep-related complex behaviors (rare)", "Amnesia"],
        "contraindications": ["Severe hepatic impairment", "Sleep apnea (untreated)", "Myasthenia gravis"],
        "drug_interactions": ["CNS depressants", "Alcohol", "CYP3A4 inhibitors"],
        "food_interactions": ["Do not take with or right after a meal (delays onset)"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No adjustment usually needed",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature, away from moisture",
        "overdose": "Seek emergency care. Flumazenil may reverse effects.",
        "missed_dose": "Only take if a full night's sleep (7-8 hrs) remains; otherwise skip.",
        "alternatives": ["Eszopiclone", "Trazodone", "Melatonin", "Doxepin"],
        "price_inr": "₹30–120 per strip",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Prescription required; short-term use only",
        "condition": "Insomnia",
    },
    "Ibuprofen": {
        "generic_name": "Ibuprofen",
        "brand_names": ["Advil", "Motrin", "Brufen"],
        "drug_class": "NSAID (Nonsteroidal Anti-Inflammatory Drug)",
        "description": "Ibuprofen relieves pain, fever, and inflammation by inhibiting cyclooxygenase (COX) enzymes and reducing prostaglandin production.",
        "uses": ["Pain relief", "Fever", "Inflammation", "Headache", "Menstrual cramps", "Arthritis"],
        "dosage": {"adult": "200–400 mg every 4–6 hours as needed", "max": "1200 mg/day (OTC); up to 3200 mg/day under medical supervision"},
        "side_effects": ["Stomach upset", "Heartburn", "Nausea", "GI bleeding (long-term/high dose)", "Increased blood pressure"],
        "contraindications": ["Active GI bleeding/ulcer", "Severe heart failure", "Third trimester pregnancy", "Aspirin/NSAID allergy"],
        "drug_interactions": ["Aspirin", "Anticoagulants (warfarin)", "ACE inhibitors/ARBs", "Lithium", "Methotrexate"],
        "food_interactions": ["Take with food or milk to reduce GI irritation"],
        "pregnancy": "Category C (D in 3rd trimester) - Avoid in late pregnancy",
        "breastfeeding": "Generally compatible (preferred NSAID while breastfeeding)",
        "kidney_warning": "Use with caution; avoid in significant renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature, away from moisture",
        "overdose": "Contact poison control. Monitor renal function and GI symptoms.",
        "missed_dose": "Take as soon as remembered; this is usually taken as needed.",
        "alternatives": ["Naproxen", "Acetaminophen", "Celecoxib", "Diclofenac"],
        "price_inr": "₹10–40 per strip",
        "prescription_required": False,
        "manufacturer": "Various",
        "availability": "Widely available (OTC)",
        "condition": "Pain",
    },
}

# ─────────────────────────────────────────────────────────────────
# Additional entries — standard, general reference (patient-leaflet
# level) information for the remaining drugs present in the trained
# recommendation dataset, so every searchable drug returns a
# complete, non-blank report.
# ─────────────────────────────────────────────────────────────────
_EXTRA = {
    "Albuterol": dict(_CURATED["Salbutamol"], generic_name="Albuterol Sulfate (Salbutamol)",
                       brand_names=["Proventil", "ProAir", "Ventolin"]),
    "Alprazolam": {
        "generic_name": "Alprazolam", "brand_names": ["Xanax", "Alprax", "Restyl"],
        "drug_class": "Benzodiazepine / Anxiolytic",
        "description": "Alprazolam is a short-acting benzodiazepine used for the short-term relief of anxiety and panic disorder.",
        "uses": ["Anxiety disorders", "Panic disorder", "Short-term anxiety relief"],
        "dosage": {"adult": "0.25–0.5 mg three times daily", "max": "4 mg/day"},
        "side_effects": ["Drowsiness", "Dizziness", "Dependence with prolonged use", "Memory impairment"],
        "contraindications": ["Narrow-angle glaucoma", "Concurrent ketoconazole/itraconazole"],
        "drug_interactions": ["Opioids", "Alcohol", "CYP3A4 inhibitors", "Other CNS depressants"],
        "food_interactions": ["Avoid grapefruit juice", "Avoid alcohol"],
        "pregnancy": "Category D - Risk of fetal harm",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Use with caution",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature, away from moisture; Schedule IV controlled substance",
        "overdose": "Seek emergency care. Flumazenil is the antidote.",
        "missed_dose": "Take as soon as remembered; do not double dose.",
        "alternatives": ["Lorazepam", "Clonazepam", "Buspirone"],
        "price_inr": "₹10–50 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Prescription required; controlled substance", "condition": "Anxiety",
    },
    "Amitriptyline": {
        "generic_name": "Amitriptyline Hydrochloride", "brand_names": ["Elavil", "Tryptomer"],
        "drug_class": "Tricyclic Antidepressant (TCA)",
        "description": "Amitriptyline is a tricyclic antidepressant also widely used at low doses for chronic pain and migraine prevention.",
        "uses": ["Migraine prevention", "Depression", "Neuropathic pain", "Chronic tension headache"],
        "dosage": {"adult": "10–25 mg at bedtime (migraine prevention); up to 150 mg/day (depression)", "max": "150–300 mg/day"},
        "side_effects": ["Dry mouth", "Drowsiness", "Weight gain", "Constipation", "Blurred vision"],
        "contraindications": ["Recent MI", "Concurrent MAOIs", "Severe arrhythmia"],
        "drug_interactions": ["MAOIs", "SSRIs", "Tramadol", "Alcohol"],
        "food_interactions": ["Avoid alcohol"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — cardiotoxicity risk. Seek immediate care.",
        "missed_dose": "Take as soon as remembered unless close to next dose.",
        "alternatives": ["Propranolol", "Topiramate", "Venlafaxine"],
        "price_inr": "₹10–40 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Migraine",
    },
    "Armour Thyroid": {
        "generic_name": "Desiccated Thyroid Extract (Porcine)", "brand_names": ["Armour Thyroid", "Nature-Throid"],
        "drug_class": "Natural Thyroid Hormone Replacement",
        "description": "Armour Thyroid is a natural desiccated thyroid extract containing both T4 and T3 hormones, used as an alternative to synthetic levothyroxine.",
        "uses": ["Hypothyroidism"],
        "dosage": {"adult": "30–60 mg once daily (starting), titrated by TSH", "max": "180 mg/day"},
        "side_effects": ["Palpitations", "Weight loss", "Tremors", "Insomnia", "Heat intolerance (if over-replaced)"],
        "contraindications": ["Untreated adrenal insufficiency", "Recent MI", "Thyrotoxicosis"],
        "drug_interactions": ["Calcium/iron supplements", "Warfarin", "PPIs"],
        "food_interactions": ["Take on an empty stomach, 30-60 min before breakfast"],
        "pregnancy": "Generally considered safe with monitoring",
        "breastfeeding": "Compatible",
        "kidney_warning": "No specific adjustment",
        "liver_warning": "Monitor thyroid levels closely",
        "storage": "Store below 25°C, protect from light and moisture",
        "overdose": "Seek emergency care; risk of thyrotoxic crisis.",
        "missed_dose": "Take as soon as remembered unless near next dose.",
        "alternatives": ["Levothyroxine", "Liothyronine"],
        "price_inr": "Consult pharmacist (imported product)",
        "prescription_required": True, "manufacturer": "Allergan / various",
        "availability": "Limited availability", "condition": "Hypothyroidism",
    },
    "Azithromycin": {
        "generic_name": "Azithromycin", "brand_names": ["Zithromax", "Azee", "Z-Pak"],
        "drug_class": "Macrolide Antibiotic",
        "description": "Azithromycin is a broad-spectrum macrolide antibiotic that inhibits bacterial protein synthesis, commonly given as a short 3–5 day course.",
        "uses": ["Respiratory tract infections", "Skin infections", "STIs (chlamydia)", "Ear infections"],
        "dosage": {"adult": "500 mg on day 1, then 250 mg once daily for 4 days (typical course)", "max": "500 mg/day"},
        "side_effects": ["Diarrhea", "Nausea", "Abdominal pain", "QT prolongation (rare)"],
        "contraindications": ["Macrolide allergy", "History of cholestatic jaundice with azithromycin"],
        "drug_interactions": ["Warfarin", "Digoxin", "QT-prolonging drugs", "Antacids (reduce absorption)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Compatible",
        "kidney_warning": "No dose adjustment for mild-moderate impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature; reconstituted suspension refrigerate",
        "overdose": "Supportive care; monitor GI and cardiac symptoms.",
        "missed_dose": "Take as soon as remembered; complete the full course.",
        "alternatives": ["Amoxicillin", "Doxycycline", "Clarithromycin"],
        "price_inr": "₹80–200 per course",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Infection",
    },
    "Budesonide": {
        "generic_name": "Budesonide", "brand_names": ["Pulmicort", "Budecort", "Rhinocort"],
        "drug_class": "Inhaled Corticosteroid (ICS)",
        "description": "Budesonide is an inhaled corticosteroid that reduces airway inflammation for long-term asthma control (not for acute attacks).",
        "uses": ["Asthma (maintenance)", "COPD maintenance", "Allergic rhinitis (nasal form)"],
        "dosage": {"adult": "200–400 mcg twice daily (inhaled)", "max": "800 mcg twice daily (severe asthma)"},
        "side_effects": ["Oral thrush", "Hoarse voice", "Throat irritation", "Cough"],
        "contraindications": ["Untreated fungal/bacterial/viral respiratory infection"],
        "drug_interactions": ["CYP3A4 inhibitors (ketoconazole, ritonavir)"],
        "food_interactions": ["Rinse mouth after use to prevent thrush"],
        "pregnancy": "Category B - Preferred ICS in pregnancy",
        "breastfeeding": "Compatible",
        "kidney_warning": "No adjustment needed",
        "liver_warning": "Use with caution in severe hepatic impairment",
        "storage": "Store at room temperature, protect from moisture",
        "overdose": "Rarely dangerous acutely; long-term overuse risks adrenal suppression.",
        "missed_dose": "Take as soon as remembered; this is a maintenance medication, not a rescue inhaler.",
        "alternatives": ["Fluticasone", "Montelukast", "Salmeterol (combination)"],
        "price_inr": "₹150–400 per inhaler",
        "prescription_required": True, "manufacturer": "AstraZeneca / various",
        "availability": "Widely available", "condition": "Asthma",
    },
    "Bupropion": {
        "generic_name": "Bupropion Hydrochloride", "brand_names": ["Wellbutrin", "Zyban"],
        "drug_class": "NDRI (Norepinephrine-Dopamine Reuptake Inhibitor)",
        "description": "Bupropion is an atypical antidepressant that works on dopamine and norepinephrine rather than serotonin, and is also used for smoking cessation.",
        "uses": ["Major Depressive Disorder", "Seasonal Affective Disorder", "Smoking cessation"],
        "dosage": {"adult": "150–300 mg/day (extended-release)", "max": "450 mg/day"},
        "side_effects": ["Dry mouth", "Insomnia", "Headache", "Weight loss", "Seizure risk (dose-dependent)"],
        "contraindications": ["Seizure disorder", "Eating disorders (anorexia/bulimia)", "Abrupt alcohol/sedative withdrawal"],
        "drug_interactions": ["MAOIs", "Other drugs lowering seizure threshold", "CYP2D6 substrates"],
        "food_interactions": ["Avoid alcohol"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Reduce dose in renal impairment",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — seizure risk. Seek immediate care.",
        "missed_dose": "Take as soon as remembered; avoid dosing late in the day (insomnia risk).",
        "alternatives": ["Sertraline", "Fluoxetine", "Venlafaxine"],
        "price_inr": "₹60–180 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Depression",
    },
    "Buspirone": {
        "generic_name": "Buspirone Hydrochloride", "brand_names": ["Buspar"],
        "drug_class": "Azapirone Anxiolytic (Non-Benzodiazepine)",
        "description": "Buspirone is a non-sedating, non-addictive anxiolytic used for generalized anxiety disorder, with effects taking 2-4 weeks to develop.",
        "uses": ["Generalized Anxiety Disorder"],
        "dosage": {"adult": "7.5 mg twice daily, titrated to 15–30 mg/day", "max": "60 mg/day"},
        "side_effects": ["Dizziness", "Nausea", "Headache", "Nervousness"],
        "contraindications": ["Concurrent MAOIs"],
        "drug_interactions": ["MAOIs", "CYP3A4 inhibitors (grapefruit, azoles)", "Serotonergic drugs"],
        "food_interactions": ["Avoid grapefruit juice", "Take consistently with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution in renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control; generally low toxicity in overdose.",
        "missed_dose": "Take as soon as remembered; consistent daily dosing needed for effect.",
        "alternatives": ["Lorazepam", "Sertraline", "Escitalopram"],
        "price_inr": "₹40–120 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Anxiety",
    },
    "Celecoxib": {
        "generic_name": "Celecoxib", "brand_names": ["Celebrex", "Celact"],
        "drug_class": "COX-2 Selective NSAID",
        "description": "Celecoxib selectively inhibits COX-2 to relieve pain and inflammation with a lower risk of GI bleeding than non-selective NSAIDs.",
        "uses": ["Osteoarthritis", "Rheumatoid arthritis", "Acute pain", "Menstrual pain"],
        "dosage": {"adult": "100–200 mg once or twice daily", "max": "400 mg/day"},
        "side_effects": ["Stomach upset", "Headache", "Increased blood pressure", "Edema"],
        "contraindications": ["Sulfonamide allergy", "Active GI bleeding", "Severe heart failure", "Post-CABG pain"],
        "drug_interactions": ["Warfarin", "ACE inhibitors/ARBs", "Lithium", "Fluconazole"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C (D in 3rd trimester) - Avoid in late pregnancy",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution; avoid in significant renal impairment",
        "liver_warning": "Reduce dose in moderate hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control. Monitor renal and GI function.",
        "missed_dose": "Take as soon as remembered; skip if near next dose.",
        "alternatives": ["Ibuprofen", "Naproxen", "Acetaminophen"],
        "price_inr": "₹80–200 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Pain",
    },
    "Cephalexin": {
        "generic_name": "Cephalexin", "brand_names": ["Keflex", "Sporidex"],
        "drug_class": "First-Generation Cephalosporin Antibiotic",
        "description": "Cephalexin is a cephalosporin antibiotic that inhibits bacterial cell wall synthesis, commonly used for skin and respiratory infections.",
        "uses": ["Skin infections", "Respiratory tract infections", "UTIs", "Bone infections"],
        "dosage": {"adult": "250–500 mg every 6 hours", "max": "4 g/day"},
        "side_effects": ["Diarrhea", "Nausea", "Skin rash", "Yeast infections"],
        "contraindications": ["Cephalosporin allergy", "Severe penicillin allergy (cross-reactivity risk)"],
        "drug_interactions": ["Metformin", "Warfarin", "Probenecid"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Compatible",
        "kidney_warning": "Reduce dose in renal impairment",
        "liver_warning": "No specific adjustment needed",
        "storage": "Room temperature; reconstituted suspension refrigerate, discard after 14 days",
        "overdose": "Supportive care.",
        "missed_dose": "Take as soon as remembered; complete the full course.",
        "alternatives": ["Amoxicillin", "Azithromycin", "Doxycycline"],
        "price_inr": "₹40–100 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Infection",
    },
    "Ciprofloxacin": {
        "generic_name": "Ciprofloxacin", "brand_names": ["Cipro", "Ciplox"],
        "drug_class": "Fluoroquinolone Antibiotic",
        "description": "Ciprofloxacin is a broad-spectrum fluoroquinolone antibiotic that inhibits bacterial DNA gyrase, reserved for infections not responsive to first-line agents.",
        "uses": ["UTIs", "Respiratory infections", "GI infections", "Skin infections"],
        "dosage": {"adult": "250–750 mg twice daily", "max": "1500 mg/day"},
        "side_effects": ["Nausea", "Diarrhea", "Tendon rupture (rare)", "Photosensitivity", "QT prolongation"],
        "contraindications": ["Fluoroquinolone allergy", "Tendon disorders", "Myasthenia gravis", "Pregnancy"],
        "drug_interactions": ["Antacids/dairy (reduce absorption)", "Warfarin", "Theophylline", "QT-prolonging drugs"],
        "food_interactions": ["Avoid dairy products and calcium-fortified juices near dosing"],
        "pregnancy": "Category C - Avoid unless essential",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Reduce dose in renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature, protect from light",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered; complete the full course.",
        "alternatives": ["Amoxicillin", "Doxycycline", "Azithromycin"],
        "price_inr": "₹40–120 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Infection",
    },
    "Clonazepam": {
        "generic_name": "Clonazepam", "brand_names": ["Klonopin", "Rivotril"],
        "drug_class": "Benzodiazepine / Anxiolytic",
        "description": "Clonazepam is a long-acting benzodiazepine used for panic disorder and certain seizure types.",
        "uses": ["Panic disorder", "Anxiety disorders", "Seizure disorders"],
        "dosage": {"adult": "0.25–0.5 mg twice daily, titrated", "max": "4 mg/day"},
        "side_effects": ["Drowsiness", "Dizziness", "Fatigue", "Dependence with prolonged use"],
        "contraindications": ["Narrow-angle glaucoma", "Severe hepatic impairment"],
        "drug_interactions": ["Opioids", "Alcohol", "Other CNS depressants"],
        "food_interactions": ["Avoid alcohol"],
        "pregnancy": "Category D - Risk of fetal harm",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Use with caution",
        "liver_warning": "Contraindicated in severe hepatic impairment",
        "storage": "Store at room temperature; Schedule IV controlled substance",
        "overdose": "Seek emergency care. Flumazenil is the antidote.",
        "missed_dose": "Take as soon as remembered; do not double dose.",
        "alternatives": ["Lorazepam", "Alprazolam", "Buspirone"],
        "price_inr": "₹15–60 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Prescription required; controlled substance", "condition": "Anxiety",
    },
    "Doxepin": {
        "generic_name": "Doxepin Hydrochloride", "brand_names": ["Silenor", "Sinequan"],
        "drug_class": "Tricyclic Antidepressant (low-dose used for insomnia)",
        "description": "Doxepin at low doses selectively blocks histamine receptors to help maintain sleep; higher doses are used as an antidepressant.",
        "uses": ["Insomnia (sleep maintenance)", "Depression (higher doses)"],
        "dosage": {"adult": "3–6 mg at bedtime (insomnia)", "max": "6 mg/day (insomnia indication)"},
        "side_effects": ["Drowsiness (next-day)", "Dry mouth", "Nausea"],
        "contraindications": ["Severe urinary retention", "Untreated narrow-angle glaucoma", "Concurrent MAOIs"],
        "drug_interactions": ["MAOIs", "CNS depressants", "Cimetidine"],
        "food_interactions": ["Avoid taking within 3 hours of a meal"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Not recommended",
        "kidney_warning": "No specific adjustment for low-dose use",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency at high (antidepressant) doses — seek immediate care.",
        "missed_dose": "Only take if a full night's sleep remains; otherwise skip.",
        "alternatives": ["Zolpidem", "Trazodone", "Eszopiclone", "Melatonin"],
        "price_inr": "₹50–150 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Insomnia",
    },
    "Doxycycline": {
        "generic_name": "Doxycycline Hyclate", "brand_names": ["Vibramycin", "Doxy-1"],
        "drug_class": "Tetracycline Antibiotic",
        "description": "Doxycycline is a broad-spectrum tetracycline antibiotic that inhibits bacterial protein synthesis, also used for acne and malaria prophylaxis.",
        "uses": ["Respiratory infections", "Acne", "Tick-borne illnesses", "Malaria prevention"],
        "dosage": {"adult": "100 mg once or twice daily", "max": "200 mg/day"},
        "side_effects": ["Photosensitivity", "Nausea", "Esophageal irritation", "Tooth discoloration (children)"],
        "contraindications": ["Pregnancy", "Children under 8 years", "Tetracycline allergy"],
        "drug_interactions": ["Antacids/dairy/iron (reduce absorption)", "Warfarin", "Oral contraceptives"],
        "food_interactions": ["Avoid dairy, antacids, and iron near dosing", "Take with a full glass of water, stay upright 30 min"],
        "pregnancy": "Category D - Contraindicated (affects fetal bone/teeth)",
        "breastfeeding": "Avoid if possible",
        "kidney_warning": "No dose adjustment usually needed",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature, protect from light",
        "overdose": "Supportive care.",
        "missed_dose": "Take as soon as remembered; complete the full course.",
        "alternatives": ["Amoxicillin", "Azithromycin", "Cephalexin"],
        "price_inr": "₹30–90 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Infection",
    },
    "Escitalopram": {
        "generic_name": "Escitalopram Oxalate", "brand_names": ["Lexapro", "Nexito"],
        "drug_class": "SSRI (Selective Serotonin Reuptake Inhibitor)",
        "description": "Escitalopram is an SSRI antidepressant, one of the most selective serotonin reuptake inhibitors, used for depression and generalized anxiety disorder.",
        "uses": ["Depression", "Anxiety", "Generalized Anxiety Disorder"],
        "dosage": {"adult": "10 mg once daily, may increase to 20 mg/day", "max": "20 mg/day"},
        "side_effects": ["Nausea", "Insomnia", "Sexual dysfunction", "Fatigue", "Dry mouth"],
        "contraindications": ["MAOIs", "Pimozide"],
        "drug_interactions": ["MAOIs", "NSAIDs (bleeding risk)", "Other serotonergic drugs"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C - Weigh risk/benefit",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No adjustment needed for mild-moderate impairment",
        "liver_warning": "Use lower doses in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care. Serotonin syndrome risk.",
        "missed_dose": "Take as soon as remembered unless near next dose.",
        "alternatives": ["Sertraline", "Fluoxetine", "Venlafaxine"],
        "price_inr": "₹60–180 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Depression",
    },
    "Esomeprazole": {
        "generic_name": "Esomeprazole Magnesium", "brand_names": ["Nexium", "Esoz"],
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "description": "Esomeprazole is the S-isomer of omeprazole, a PPI that reduces stomach acid production for GERD and ulcer treatment.",
        "uses": ["GERD", "Peptic ulcers", "H. pylori eradication (combination therapy)"],
        "dosage": {"adult": "20–40 mg once daily", "max": "40 mg twice daily (severe cases)"},
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Hypomagnesemia (long-term)"],
        "contraindications": ["Rilpivirine (HIV)", "PPI hypersensitivity"],
        "drug_interactions": ["Clopidogrel", "Methotrexate", "Warfarin"],
        "food_interactions": ["Take at least 1 hour before a meal"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Reduce dose in severe hepatic impairment",
        "storage": "Store below 30°C in original packaging",
        "overdose": "Generally low toxicity. Supportive care.",
        "missed_dose": "Take as soon as remembered before the next meal.",
        "alternatives": ["Omeprazole", "Pantoprazole", "Lansoprazole"],
        "price_inr": "₹80–200 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available", "condition": "GERD",
    },
    "Eszopiclone": {
        "generic_name": "Eszopiclone", "brand_names": ["Lunesta"],
        "drug_class": "Non-Benzodiazepine Sedative-Hypnotic (Z-drug)",
        "description": "Eszopiclone is a sedative-hypnotic used for insomnia, with a longer duration of action than zolpidem, suitable for sleep-maintenance issues.",
        "uses": ["Insomnia (sleep onset and maintenance)"],
        "dosage": {"adult": "1–3 mg at bedtime", "elderly": "1 mg", "max": "3 mg/day"},
        "side_effects": ["Unpleasant taste", "Drowsiness", "Dizziness", "Headache"],
        "contraindications": ["Known hypersensitivity"],
        "drug_interactions": ["CNS depressants", "Alcohol", "CYP3A4 inhibitors"],
        "food_interactions": ["Avoid taking with or immediately after a high-fat meal"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No adjustment usually needed",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care.",
        "missed_dose": "Only take if a full night's sleep remains; otherwise skip.",
        "alternatives": ["Zolpidem", "Trazodone", "Melatonin"],
        "price_inr": "Consult pharmacist (imported product)",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Limited availability", "condition": "Insomnia",
    },
    "Ezetimibe": {
        "generic_name": "Ezetimibe", "brand_names": ["Zetia", "Ezetrol"],
        "drug_class": "Cholesterol Absorption Inhibitor",
        "description": "Ezetimibe lowers LDL cholesterol by blocking absorption of dietary and biliary cholesterol in the small intestine, often combined with a statin.",
        "uses": ["High Cholesterol", "Combination therapy with statins"],
        "dosage": {"adult": "10 mg once daily", "max": "10 mg/day"},
        "side_effects": ["Diarrhea", "Muscle pain (especially combined with statin)", "Fatigue"],
        "contraindications": ["Active liver disease (combination with statin)"],
        "drug_interactions": ["Cyclosporine", "Fibrates", "Statins (additive myopathy risk)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Not recommended",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered.",
        "alternatives": ["Atorvastatin", "Rosuvastatin", "Simvastatin"],
        "price_inr": "₹90–220 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "High Cholesterol",
    },
    "Fluoxetine": {
        "generic_name": "Fluoxetine Hydrochloride", "brand_names": ["Prozac", "Fludac"],
        "drug_class": "SSRI (Selective Serotonin Reuptake Inhibitor)",
        "description": "Fluoxetine was the first widely-used SSRI, notable for its long half-life, used for depression, OCD, and panic disorder.",
        "uses": ["Depression", "OCD", "Panic disorder", "Bulimia nervosa"],
        "dosage": {"adult": "20 mg once daily, may increase", "max": "80 mg/day"},
        "side_effects": ["Nausea", "Insomnia", "Anxiety", "Sexual dysfunction", "Appetite changes"],
        "contraindications": ["MAOIs", "Pimozide", "Thioridazine"],
        "drug_interactions": ["MAOIs", "Warfarin", "Tramadol", "Triptans"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C - Weigh risk/benefit",
        "breastfeeding": "Use with caution (long half-life)",
        "kidney_warning": "No adjustment needed for mild-moderate impairment",
        "liver_warning": "Use lower/less frequent doses in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care. Serotonin syndrome risk.",
        "missed_dose": "Take as soon as remembered unless near next dose.",
        "alternatives": ["Sertraline", "Escitalopram", "Venlafaxine"],
        "price_inr": "₹30–100 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Depression",
    },
    "Fluticasone": {
        "generic_name": "Fluticasone Propionate", "brand_names": ["Flonase", "Flovent", "Flutivate"],
        "drug_class": "Inhaled/Intranasal Corticosteroid",
        "description": "Fluticasone is a corticosteroid used as an inhaler for asthma maintenance or a nasal spray for allergic rhinitis, reducing airway/nasal inflammation.",
        "uses": ["Asthma (maintenance)", "Allergic rhinitis"],
        "dosage": {"adult": "88–440 mcg twice daily (inhaled)", "max": "880 mcg twice daily (severe asthma)"},
        "side_effects": ["Oral thrush", "Hoarseness", "Nasal irritation (spray)", "Headache"],
        "contraindications": ["Untreated respiratory infection"],
        "drug_interactions": ["CYP3A4 inhibitors (ritonavir, ketoconazole)"],
        "food_interactions": ["Rinse mouth after inhaler use"],
        "pregnancy": "Category C - Generally considered low risk",
        "breastfeeding": "Compatible",
        "kidney_warning": "No adjustment needed",
        "liver_warning": "Use with caution in severe hepatic impairment",
        "storage": "Store at room temperature, protect from moisture",
        "overdose": "Rarely dangerous acutely; long-term overuse risks adrenal suppression.",
        "missed_dose": "Take as soon as remembered; maintenance medication, not a rescue inhaler.",
        "alternatives": ["Budesonide", "Montelukast", "Salmeterol"],
        "price_inr": "₹150–350 per inhaler/spray",
        "prescription_required": True, "manufacturer": "GSK / various",
        "availability": "Widely available", "condition": "Asthma",
    },
    "Glipizide": {
        "generic_name": "Glipizide", "brand_names": ["Glucotrol", "Glynase"],
        "drug_class": "Sulfonylurea Antidiabetic",
        "description": "Glipizide stimulates the pancreas to release more insulin, used as a second-line agent for type 2 diabetes.",
        "uses": ["Type 2 Diabetes"],
        "dosage": {"adult": "5 mg once daily, titrated", "max": "40 mg/day"},
        "side_effects": ["Hypoglycemia", "Weight gain", "Nausea", "Dizziness"],
        "contraindications": ["Type 1 diabetes", "Diabetic ketoacidosis", "Sulfonylurea allergy"],
        "drug_interactions": ["Alcohol", "Beta-blockers (mask hypoglycemia)", "NSAIDs"],
        "food_interactions": ["Take 30 minutes before a meal"],
        "pregnancy": "Category C - Insulin generally preferred",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Use with caution in renal impairment (hypoglycemia risk)",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — severe hypoglycemia risk. Seek immediate care.",
        "missed_dose": "Skip if close to next meal/dose; do not double dose.",
        "alternatives": ["Metformin", "Sitagliptin", "Empagliflozin"],
        "price_inr": "₹20–70 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Diabetes Type 2",
    },
    "Hydrochlorothiazide": {
        "generic_name": "Hydrochlorothiazide (HCTZ)", "brand_names": ["Microzide", "Hydrodiuril"],
        "drug_class": "Thiazide Diuretic",
        "description": "Hydrochlorothiazide is a thiazide diuretic that lowers blood pressure by reducing sodium and water reabsorption in the kidneys.",
        "uses": ["Hypertension", "Edema", "Heart failure (adjunct)"],
        "dosage": {"adult": "12.5–25 mg once daily", "max": "50 mg/day"},
        "side_effects": ["Increased urination", "Hypokalemia", "Dizziness", "Increased blood glucose/uric acid"],
        "contraindications": ["Anuria", "Sulfonamide allergy"],
        "drug_interactions": ["Lithium", "NSAIDs", "Digoxin", "Other antihypertensives"],
        "food_interactions": ["Take in the morning to avoid nighttime urination"],
        "pregnancy": "Category B/D depending on trimester - Use with caution",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Monitor renal function and electrolytes",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control. Monitor electrolytes and blood pressure.",
        "missed_dose": "Take as soon as remembered; skip if near next dose.",
        "alternatives": ["Lisinopril", "Amlodipine", "Losartan"],
        "price_inr": "₹10–40 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Hypertension",
    },
    "Januvia": {
        "generic_name": "Sitagliptin", "brand_names": ["Januvia"],
        "drug_class": "DPP-4 Inhibitor (Gliptin)",
        "description": "Sitagliptin increases incretin levels, which increase insulin release and decrease glucagon levels, used for type 2 diabetes.",
        "uses": ["Type 2 Diabetes"],
        "dosage": {"adult": "100 mg once daily", "max": "100 mg/day"},
        "side_effects": ["Upper respiratory infection symptoms", "Headache", "Pancreatitis (rare)"],
        "contraindications": ["Type 1 diabetes", "History of pancreatitis (caution)"],
        "drug_interactions": ["Digoxin (mild)", "Other antidiabetics (hypoglycemia risk)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Use only if clearly needed",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Reduce dose based on renal function",
        "liver_warning": "No specific adjustment needed",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered; skip if near next dose.",
        "alternatives": ["Metformin", "Jardiance", "Glipizide"],
        "price_inr": "₹350–600 per strip",
        "prescription_required": True, "manufacturer": "MSD",
        "availability": "Available at major pharmacies", "condition": "Diabetes Type 2",
    },
    "Jardiance": {
        "generic_name": "Empagliflozin", "brand_names": ["Jardiance"],
        "drug_class": "SGLT-2 Inhibitor",
        "description": "Empagliflozin lowers blood glucose by blocking glucose reabsorption in the kidney, causing excess glucose to be excreted in urine; also reduces cardiovascular risk.",
        "uses": ["Type 2 Diabetes", "Heart failure", "Cardiovascular risk reduction"],
        "dosage": {"adult": "10 mg once daily", "max": "25 mg/day"},
        "side_effects": ["Genital yeast infections", "UTI", "Increased urination", "Dehydration"],
        "contraindications": ["Type 1 diabetes", "Severe renal impairment", "Dialysis"],
        "drug_interactions": ["Diuretics (dehydration risk)", "Insulin/sulfonylureas (hypoglycemia risk)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Not recommended",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Not recommended if eGFR persistently <20-30",
        "liver_warning": "No dose adjustment needed",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered; skip if near next dose.",
        "alternatives": ["Metformin", "Januvia", "Glipizide"],
        "price_inr": "₹400–700 per strip",
        "prescription_required": True, "manufacturer": "Boehringer Ingelheim",
        "availability": "Available at major pharmacies", "condition": "Diabetes Type 2",
    },
    "Lansoprazole": {
        "generic_name": "Lansoprazole", "brand_names": ["Prevacid", "Lanzol"],
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "description": "Lansoprazole reduces stomach acid production by blocking the gastric proton pump, used for GERD and ulcer healing.",
        "uses": ["GERD", "Peptic ulcers", "H. pylori eradication"],
        "dosage": {"adult": "15–30 mg once daily", "max": "60 mg/day (severe cases)"},
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Hypomagnesemia (long-term)"],
        "contraindications": ["Rilpivirine (HIV)", "PPI hypersensitivity"],
        "drug_interactions": ["Clopidogrel", "Warfarin", "Theophylline"],
        "food_interactions": ["Take before a meal"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Reduce dose in severe hepatic impairment",
        "storage": "Store below 25°C in original packaging",
        "overdose": "Generally low toxicity. Supportive care.",
        "missed_dose": "Take as soon as remembered before the next meal.",
        "alternatives": ["Omeprazole", "Pantoprazole", "Esomeprazole"],
        "price_inr": "₹40–110 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available", "condition": "GERD",
    },
    "Liothyronine": {
        "generic_name": "Liothyronine Sodium (T3)", "brand_names": ["Cytomel"],
        "drug_class": "Thyroid Hormone Replacement",
        "description": "Liothyronine is a synthetic form of triiodothyronine (T3), the active thyroid hormone, used alone or combined with levothyroxine for hypothyroidism.",
        "uses": ["Hypothyroidism", "Myxedema coma (IV form)"],
        "dosage": {"adult": "25 mcg once daily, titrated", "max": "75 mcg/day"},
        "side_effects": ["Palpitations", "Tremors", "Insomnia", "Weight loss (excess dose)"],
        "contraindications": ["Untreated adrenal insufficiency", "Recent MI", "Thyrotoxicosis"],
        "drug_interactions": ["Warfarin", "Digoxin", "Antidiabetic agents"],
        "food_interactions": ["Take on an empty stomach"],
        "pregnancy": "Generally considered safe with monitoring",
        "breastfeeding": "Compatible",
        "kidney_warning": "No specific adjustment",
        "liver_warning": "Monitor thyroid levels closely",
        "storage": "Store below 25°C, protect from light",
        "overdose": "Seek emergency care; risk of thyrotoxic crisis.",
        "missed_dose": "Take as soon as remembered unless near next dose.",
        "alternatives": ["Levothyroxine", "Armour Thyroid"],
        "price_inr": "Consult pharmacist (imported product)",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Limited availability", "condition": "Hypothyroidism",
    },
    "Losartan": {
        "generic_name": "Losartan Potassium", "brand_names": ["Cozaar", "Losar"],
        "drug_class": "Angiotensin II Receptor Blocker (ARB)",
        "description": "Losartan blocks the angiotensin II receptor to relax blood vessels and lower blood pressure, often used when ACE inhibitors cause cough.",
        "uses": ["Hypertension", "Diabetic nephropathy", "Heart failure"],
        "dosage": {"adult": "50 mg once daily", "max": "100 mg/day"},
        "side_effects": ["Dizziness", "Hyperkalemia", "Fatigue", "Upper respiratory symptoms"],
        "contraindications": ["Pregnancy", "Bilateral renal artery stenosis", "Concurrent aliskiren in diabetics"],
        "drug_interactions": ["NSAIDs", "Potassium-sparing diuretics", "Lithium"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category D - Contraindicated",
        "breastfeeding": "Not recommended",
        "kidney_warning": "Monitor renal function and potassium",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control. Monitor blood pressure.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Lisinopril", "Amlodipine", "Hydrochlorothiazide"],
        "price_inr": "₹30–90 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Hypertension",
    },
    "Melatonin": {
        "generic_name": "Melatonin", "brand_names": ["Circadin", "Melatol"],
        "drug_class": "Hormone Supplement / Sleep Aid",
        "description": "Melatonin is a hormone that regulates the sleep-wake cycle; supplemental melatonin can help with sleep-onset insomnia and jet lag.",
        "uses": ["Insomnia (sleep onset)", "Jet lag", "Circadian rhythm disorders"],
        "dosage": {"adult": "0.5–5 mg 30-60 minutes before bedtime", "max": "10 mg/day"},
        "side_effects": ["Drowsiness", "Headache", "Dizziness", "Daytime grogginess (high doses)"],
        "contraindications": ["Autoimmune disease (caution)", "Concurrent immunosuppressants"],
        "drug_interactions": ["Warfarin", "Sedatives", "Immunosuppressants"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Insufficient data - use with caution",
        "breastfeeding": "Insufficient data - use with caution",
        "kidney_warning": "No specific adjustment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Generally low toxicity.",
        "missed_dose": "Only take if a full night's sleep remains.",
        "alternatives": ["Zolpidem", "Trazodone", "Doxepin"],
        "price_inr": "₹150–350 per bottle (OTC supplement)",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available (OTC)", "condition": "Insomnia",
    },
    "Metoprolol": {
        "generic_name": "Metoprolol Tartrate/Succinate", "brand_names": ["Lopressor", "Toprol-XL", "Metolar"],
        "drug_class": "Beta-1 Selective Beta-Blocker",
        "description": "Metoprolol blocks beta-1 adrenergic receptors, slowing heart rate and reducing blood pressure and cardiac workload.",
        "uses": ["Hypertension", "Angina", "Heart failure", "Arrhythmias", "Post-MI"],
        "dosage": {"adult": "25–100 mg once or twice daily", "max": "400 mg/day"},
        "side_effects": ["Fatigue", "Bradycardia", "Dizziness", "Cold extremities"],
        "contraindications": ["Severe bradycardia", "Cardiogenic shock", "Uncontrolled heart failure", "Severe asthma"],
        "drug_interactions": ["Other antihypertensives", "Non-dihydropyridine CCBs", "Insulin (masks hypoglycemia)"],
        "food_interactions": ["Take with food consistently for extended-release forms"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No specific adjustment usually needed",
        "liver_warning": "Reduce dose in severe hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — severe bradycardia/hypotension risk.",
        "missed_dose": "Take as soon as remembered; do not stop abruptly.",
        "alternatives": ["Amlodipine", "Lisinopril", "Propranolol"],
        "price_inr": "₹20–70 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Hypertension",
    },
    "Montelukast": {
        "generic_name": "Montelukast Sodium", "brand_names": ["Singulair", "Montair"],
        "drug_class": "Leukotriene Receptor Antagonist",
        "description": "Montelukast blocks leukotriene receptors to reduce airway inflammation and bronchoconstriction, used for asthma maintenance and allergic rhinitis.",
        "uses": ["Asthma (maintenance)", "Allergic rhinitis", "Exercise-induced bronchoconstriction"],
        "dosage": {"adult": "10 mg once daily (evening)", "max": "10 mg/day"},
        "side_effects": ["Headache", "Abdominal pain", "Mood/behavior changes (rare but notable)"],
        "contraindications": ["Known hypersensitivity"],
        "drug_interactions": ["Phenobarbital", "Rifampin (reduce montelukast levels)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No adjustment needed",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature, protect from light and moisture",
        "overdose": "Contact poison control; generally low acute toxicity.",
        "missed_dose": "Take as soon as remembered; not for acute asthma attacks.",
        "alternatives": ["Budesonide", "Fluticasone", "Salmeterol"],
        "price_inr": "₹80–200 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Asthma",
    },
    "Naproxen": {
        "generic_name": "Naproxen Sodium", "brand_names": ["Aleve", "Naprosyn"],
        "drug_class": "NSAID (Nonsteroidal Anti-Inflammatory Drug)",
        "description": "Naproxen is a longer-acting NSAID that relieves pain and inflammation by inhibiting cyclooxygenase (COX) enzymes.",
        "uses": ["Pain relief", "Arthritis", "Menstrual cramps", "Inflammation"],
        "dosage": {"adult": "220–500 mg every 8-12 hours", "max": "1000 mg/day (OTC); up to 1500 mg/day under medical supervision"},
        "side_effects": ["Stomach upset", "Heartburn", "GI bleeding (long-term/high dose)", "Dizziness"],
        "contraindications": ["Active GI bleeding/ulcer", "Severe heart failure", "Third trimester pregnancy"],
        "drug_interactions": ["Aspirin", "Anticoagulants", "ACE inhibitors/ARBs", "Lithium", "Methotrexate"],
        "food_interactions": ["Take with food or milk to reduce GI irritation"],
        "pregnancy": "Category C (D in 3rd trimester) - Avoid in late pregnancy",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution; avoid in significant renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control. Monitor renal function and GI symptoms.",
        "missed_dose": "Take as soon as remembered; this is usually taken as needed.",
        "alternatives": ["Ibuprofen", "Celecoxib", "Acetaminophen"],
        "price_inr": "₹15–50 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available (OTC)", "condition": "Pain",
    },
    "Pantoprazole": {
        "generic_name": "Pantoprazole Sodium", "brand_names": ["Protonix", "Pantocid"],
        "drug_class": "Proton Pump Inhibitor (PPI)",
        "description": "Pantoprazole reduces gastric acid secretion by blocking the proton pump; has fewer drug interactions than some other PPIs.",
        "uses": ["GERD", "Peptic ulcers", "Erosive esophagitis"],
        "dosage": {"adult": "40 mg once daily", "max": "80 mg twice daily (severe cases)"},
        "side_effects": ["Headache", "Diarrhea", "Nausea", "Hypomagnesemia (long-term)"],
        "contraindications": ["Rilpivirine (HIV)", "PPI hypersensitivity"],
        "drug_interactions": ["Warfarin (mild)", "Methotrexate", "Atazanavir"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No dose adjustment needed",
        "liver_warning": "Reduce dose in severe hepatic impairment",
        "storage": "Store below 25°C in original packaging",
        "overdose": "Generally low toxicity. Supportive care.",
        "missed_dose": "Take as soon as remembered before the next meal.",
        "alternatives": ["Omeprazole", "Esomeprazole", "Lansoprazole"],
        "price_inr": "₹40–110 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available", "condition": "GERD",
    },
    "Pravastatin": {
        "generic_name": "Pravastatin Sodium", "brand_names": ["Pravachol"],
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "description": "Pravastatin lowers LDL cholesterol with a lower risk of drug interactions than other statins since it is not metabolized by CYP3A4.",
        "uses": ["High Cholesterol", "Cardiovascular prevention"],
        "dosage": {"adult": "10–40 mg once daily", "max": "80 mg/day"},
        "side_effects": ["Myalgia", "Liver enzyme elevation", "GI upset"],
        "contraindications": ["Active liver disease", "Pregnancy", "Breastfeeding"],
        "drug_interactions": ["Cyclosporine", "Gemfibrozil", "Niacin (myopathy risk)"],
        "food_interactions": ["Can be taken with or without food (no grapefruit restriction)"],
        "pregnancy": "Category X - Contraindicated",
        "breastfeeding": "Contraindicated",
        "kidney_warning": "Use lower starting dose in renal impairment",
        "liver_warning": "Contraindicated in active liver disease. Monitor LFTs.",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Atorvastatin", "Rosuvastatin", "Simvastatin"],
        "price_inr": "₹60–150 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "High Cholesterol",
    },
    "Propranolol": {
        "generic_name": "Propranolol Hydrochloride", "brand_names": ["Inderal"],
        "drug_class": "Non-Selective Beta-Blocker",
        "description": "Propranolol blocks beta-adrenergic receptors and is used for hypertension, migraine prevention, tremor, and performance anxiety.",
        "uses": ["Migraine prevention", "Hypertension", "Essential tremor", "Anxiety (situational)"],
        "dosage": {"adult": "40–160 mg/day in divided doses (migraine prevention)", "max": "240 mg/day"},
        "side_effects": ["Fatigue", "Bradycardia", "Cold extremities", "Dizziness", "Bronchospasm (asthma risk)"],
        "contraindications": ["Asthma/severe COPD", "Severe bradycardia", "Cardiogenic shock", "Uncontrolled heart failure"],
        "drug_interactions": ["Salbutamol (blocks bronchodilation)", "Verapamil/Diltiazem", "Insulin (masks hypoglycemia)"],
        "food_interactions": ["Take consistently with or without food"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Compatible with monitoring",
        "kidney_warning": "No specific adjustment usually needed",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — severe bradycardia/hypotension risk.",
        "missed_dose": "Take as soon as remembered; do not stop abruptly.",
        "alternatives": ["Topiramate", "Amitriptyline", "Metoprolol"],
        "price_inr": "₹15–50 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Migraine",
    },
    "Ranitidine": {
        "generic_name": "Ranitidine Hydrochloride", "brand_names": ["Zantac"],
        "drug_class": "H2-Receptor Antagonist",
        "description": "Ranitidine reduces stomach acid by blocking histamine H2 receptors. Note: many ranitidine products were withdrawn/recalled in various markets over NDMA contamination concerns; consult a pharmacist about current availability and PPI alternatives.",
        "uses": ["GERD", "Peptic ulcers", "Heartburn"],
        "dosage": {"adult": "150 mg twice daily or 300 mg at bedtime", "max": "300 mg/day"},
        "side_effects": ["Headache", "Constipation", "Diarrhea", "Dizziness"],
        "contraindications": ["Known hypersensitivity"],
        "drug_interactions": ["Ketoconazole (reduced absorption)", "Warfarin (mild)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Generally considered safe",
        "breastfeeding": "Compatible",
        "kidney_warning": "Reduce dose in renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature, protect from light",
        "overdose": "Generally low toxicity. Supportive care.",
        "missed_dose": "Take as soon as remembered.",
        "alternatives": ["Omeprazole", "Pantoprazole", "Famotidine"],
        "price_inr": "₹20–60 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Regulatory status varies by region — confirm with a pharmacist", "condition": "GERD",
    },
    "Rizatriptan": {
        "generic_name": "Rizatriptan Benzoate", "brand_names": ["Maxalt"],
        "drug_class": "Triptan (5-HT1 Agonist)",
        "description": "Rizatriptan is a fast-acting triptan used to treat acute migraine attacks by constricting cranial blood vessels and reducing inflammation.",
        "uses": ["Acute Migraine"],
        "dosage": {"adult": "5–10 mg per attack, may repeat after 2 hours", "max": "30 mg/24 hrs"},
        "side_effects": ["Dizziness", "Fatigue", "Chest tightness", "Nausea", "Tingling"],
        "contraindications": ["Ischemic heart disease", "Uncontrolled hypertension", "MAOIs"],
        "drug_interactions": ["MAOIs", "Propranolol (dose adjustment)", "SSRIs (serotonin syndrome risk)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution in severe renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care. Monitor cardiovascular function.",
        "missed_dose": "Take at onset of migraine. Do not take preventively.",
        "alternatives": ["Sumatriptan", "Naproxen", "Ibuprofen"],
        "price_inr": "₹150–400 per pack",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Available at pharmacies", "condition": "Migraine",
    },
    "Rosuvastatin": {
        "generic_name": "Rosuvastatin Calcium", "brand_names": ["Crestor", "Rosuvas"],
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "description": "Rosuvastatin is a potent statin that significantly lowers LDL cholesterol, often used when other statins are insufficient.",
        "uses": ["High Cholesterol", "Cardiovascular prevention"],
        "dosage": {"adult": "5–20 mg once daily", "max": "40 mg/day"},
        "side_effects": ["Myalgia", "Liver enzyme elevation", "Headache", "GI upset"],
        "contraindications": ["Active liver disease", "Pregnancy", "Breastfeeding"],
        "drug_interactions": ["Cyclosporine", "Gemfibrozil", "Warfarin"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category X - Contraindicated",
        "breastfeeding": "Contraindicated",
        "kidney_warning": "Reduce starting dose in significant renal impairment",
        "liver_warning": "Contraindicated in active liver disease. Monitor LFTs.",
        "storage": "Store at room temperature",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Atorvastatin", "Simvastatin", "Pravastatin"],
        "price_inr": "₹80–200 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "High Cholesterol",
    },
    "Salmeterol": {
        "generic_name": "Salmeterol Xinafoate", "brand_names": ["Serevent", "Seroflo (combination)"],
        "drug_class": "Long-Acting Beta-2 Agonist (LABA)",
        "description": "Salmeterol is a long-acting bronchodilator used for maintenance asthma/COPD control, always combined with an inhaled corticosteroid for asthma.",
        "uses": ["Asthma (maintenance, with ICS)", "COPD maintenance"],
        "dosage": {"adult": "50 mcg twice daily (inhaled)", "max": "100 mcg/day"},
        "side_effects": ["Tremor", "Headache", "Palpitations", "Throat irritation"],
        "contraindications": ["Use as monotherapy for asthma without ICS", "Acute bronchospasm (not a rescue inhaler)"],
        "drug_interactions": ["Beta-blockers", "MAOIs", "Other sympathomimetics"],
        "food_interactions": ["None significant"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "No adjustment needed",
        "liver_warning": "No adjustment needed",
        "storage": "Store at room temperature, protect from heat",
        "overdose": "Seek emergency care. Monitor heart rate and potassium.",
        "missed_dose": "Take as soon as remembered; not for acute symptom relief.",
        "alternatives": ["Budesonide (combination)", "Fluticasone", "Montelukast"],
        "price_inr": "₹250–500 per inhaler",
        "prescription_required": True, "manufacturer": "GSK / various",
        "availability": "Widely available", "condition": "Asthma",
    },
    "Simvastatin": {
        "generic_name": "Simvastatin", "brand_names": ["Zocor"],
        "drug_class": "HMG-CoA Reductase Inhibitor (Statin)",
        "description": "Simvastatin lowers LDL cholesterol by inhibiting HMG-CoA reductase; has more interaction potential (CYP3A4) than some newer statins.",
        "uses": ["High Cholesterol", "Cardiovascular prevention"],
        "dosage": {"adult": "10–40 mg once daily (evening)", "max": "40 mg/day (80 mg only in patients already tolerating it)"},
        "side_effects": ["Myalgia", "Liver enzyme elevation", "Rhabdomyolysis (rare, dose-dependent)"],
        "contraindications": ["Active liver disease", "Concurrent strong CYP3A4 inhibitors", "Pregnancy"],
        "drug_interactions": ["Amlodipine (dose limit 20mg)", "Amiodarone", "Macrolide antibiotics", "Grapefruit juice"],
        "food_interactions": ["Avoid grapefruit juice", "Take in the evening"],
        "pregnancy": "Category X - Contraindicated",
        "breastfeeding": "Contraindicated",
        "kidney_warning": "Use lower doses in significant renal impairment",
        "liver_warning": "Contraindicated in active liver disease. Monitor LFTs.",
        "storage": "Store at room temperature, protect from light",
        "overdose": "Contact poison control.",
        "missed_dose": "Take as soon as remembered. Do not double dose.",
        "alternatives": ["Atorvastatin", "Rosuvastatin", "Pravastatin"],
        "price_inr": "₹30–90 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "High Cholesterol",
    },
    "Topiramate": {
        "generic_name": "Topiramate", "brand_names": ["Topamax"],
        "drug_class": "Anticonvulsant (used for migraine prevention)",
        "description": "Topiramate is an anticonvulsant that is also FDA-approved for migraine prevention, thought to work by stabilizing neuronal excitability.",
        "uses": ["Migraine prevention", "Epilepsy", "Weight management (combination products)"],
        "dosage": {"adult": "25 mg once daily, titrated to 50 mg twice daily", "max": "100 mg/day (migraine)"},
        "side_effects": ["Tingling in extremities", "Cognitive slowing", "Weight loss", "Kidney stones"],
        "contraindications": ["Metabolic acidosis", "Angle-closure glaucoma"],
        "drug_interactions": ["Other CNS depressants", "Oral contraceptives (reduced efficacy)", "Metformin"],
        "food_interactions": ["Maintain adequate hydration (kidney stone risk)"],
        "pregnancy": "Category D - Risk of fetal malformations",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Reduce dose in renal impairment; hydrate well",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care.",
        "missed_dose": "Take as soon as remembered; do not stop abruptly (seizure risk).",
        "alternatives": ["Propranolol", "Amitriptyline", "Sumatriptan (acute)"],
        "price_inr": "₹60–180 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Migraine",
    },
    "Tramadol": {
        "generic_name": "Tramadol Hydrochloride", "brand_names": ["Ultram", "Tramacip"],
        "drug_class": "Opioid Analgesic (Atypical)",
        "description": "Tramadol is a centrally-acting analgesic that binds opioid receptors and also inhibits serotonin/norepinephrine reuptake, used for moderate-to-moderately-severe pain.",
        "uses": ["Moderate to moderately severe pain"],
        "dosage": {"adult": "50–100 mg every 4-6 hours as needed", "max": "400 mg/day"},
        "side_effects": ["Nausea", "Dizziness", "Constipation", "Sedation", "Seizure risk (high doses)"],
        "contraindications": ["Concurrent MAOIs", "Uncontrolled seizure disorder", "Acute intoxication with alcohol/opioids"],
        "drug_interactions": ["SSRIs/SNRIs (serotonin syndrome risk)", "MAOIs", "CNS depressants", "Warfarin"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category C - Risk of neonatal withdrawal if used near term",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Reduce dose/frequency in renal impairment",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature; controlled substance",
        "overdose": "Medical emergency — respiratory depression risk. Naloxone may partially reverse.",
        "missed_dose": "Take as soon as remembered; this is usually taken as needed.",
        "alternatives": ["Ibuprofen", "Naproxen", "Acetaminophen", "Celecoxib"],
        "price_inr": "₹30–100 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Prescription required; controlled substance in many regions", "condition": "Pain",
    },
    "Trazodone": {
        "generic_name": "Trazodone Hydrochloride", "brand_names": ["Desyrel"],
        "drug_class": "Serotonin Antagonist and Reuptake Inhibitor (SARI)",
        "description": "Trazodone is an antidepressant that is widely used off-label at low doses for insomnia due to its sedating effect.",
        "uses": ["Insomnia (low dose, off-label)", "Depression (higher doses)"],
        "dosage": {"adult": "25–100 mg at bedtime (insomnia)", "max": "400 mg/day (depression, divided doses)"},
        "side_effects": ["Drowsiness (next-day)", "Dry mouth", "Dizziness", "Priapism (rare but serious)"],
        "contraindications": ["Recovery phase of MI", "Concurrent MAOIs"],
        "drug_interactions": ["MAOIs", "Other serotonergic drugs", "CNS depressants"],
        "food_interactions": ["Take shortly after a light meal or snack to reduce dizziness"],
        "pregnancy": "Category C - Use only if clearly needed",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Use with caution in renal impairment",
        "liver_warning": "Use with caution in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care. Serotonin syndrome risk at high doses.",
        "missed_dose": "Only take if a full night's sleep remains.",
        "alternatives": ["Zolpidem", "Doxepin", "Melatonin", "Eszopiclone"],
        "price_inr": "₹30–90 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Insomnia",
    },
    "Venlafaxine": {
        "generic_name": "Venlafaxine Hydrochloride", "brand_names": ["Effexor"],
        "drug_class": "SNRI (Serotonin-Norepinephrine Reuptake Inhibitor)",
        "description": "Venlafaxine increases both serotonin and norepinephrine levels, used for depression and anxiety, especially when SSRIs are insufficient.",
        "uses": ["Depression", "Generalized Anxiety Disorder", "Panic disorder"],
        "dosage": {"adult": "75 mg/day, may increase gradually", "max": "375 mg/day"},
        "side_effects": ["Nausea", "Increased blood pressure", "Insomnia", "Sweating", "Sexual dysfunction"],
        "contraindications": ["Concurrent MAOIs", "Uncontrolled hypertension (caution)"],
        "drug_interactions": ["MAOIs", "Other serotonergic drugs", "Warfarin"],
        "food_interactions": ["Take with food"],
        "pregnancy": "Category C - Weigh risk/benefit; risk of neonatal complications near term",
        "breastfeeding": "Use with caution",
        "kidney_warning": "Reduce dose in renal impairment",
        "liver_warning": "Reduce dose in hepatic impairment",
        "storage": "Store at room temperature",
        "overdose": "Seek emergency care. Serotonin syndrome and cardiac risk.",
        "missed_dose": "Take as soon as remembered unless near next dose; do not stop abruptly (discontinuation syndrome).",
        "alternatives": ["Sertraline", "Escitalopram", "Bupropion"],
        "price_inr": "₹60–180 per strip",
        "prescription_required": True, "manufacturer": "Various",
        "availability": "Widely available", "condition": "Depression",
    },
    "Acetaminophen": {
        "generic_name": "Acetaminophen (Paracetamol)", "brand_names": ["Tylenol", "Crocin", "Calpol"],
        "drug_class": "Analgesic / Antipyretic",
        "description": "Acetaminophen relieves pain and reduces fever through central mechanisms; unlike NSAIDs it has minimal anti-inflammatory effect and does not irritate the stomach.",
        "uses": ["Pain relief", "Fever reduction", "Headache", "Osteoarthritis"],
        "dosage": {"adult": "500–1000 mg every 4-6 hours as needed", "max": "3000–4000 mg/day (do not exceed)"},
        "side_effects": ["Generally well tolerated", "Liver damage (overdose/chronic high dose)", "Rare skin reactions"],
        "contraindications": ["Severe hepatic impairment", "Chronic alcohol use (caution)"],
        "drug_interactions": ["Warfarin (high doses)", "Alcohol (liver toxicity risk)"],
        "food_interactions": ["Can be taken with or without food"],
        "pregnancy": "Category B - Preferred analgesic in pregnancy at recommended doses",
        "breastfeeding": "Compatible",
        "kidney_warning": "Use with caution in significant renal impairment",
        "liver_warning": "Avoid/reduce dose in hepatic impairment; strict max-dose adherence essential",
        "storage": "Store at room temperature",
        "overdose": "Medical emergency — can cause severe liver damage. Seek immediate care; N-acetylcysteine is the antidote.",
        "missed_dose": "Take as soon as remembered; this is usually taken as needed.",
        "alternatives": ["Ibuprofen", "Naproxen", "Celecoxib"],
        "price_inr": "₹5–25 per strip",
        "prescription_required": False, "manufacturer": "Various",
        "availability": "Widely available (OTC)", "condition": "Pain",
    },
}

# Merge curated + extra into the master database
DRUG_DATABASE = {**_CURATED, **_EXTRA}

# Case-insensitive lookup index
_LOOKUP = {name.lower(): name for name in DRUG_DATABASE}


def get_drug_info(name: str):
    """Case-insensitive lookup. Returns (canonical_name, info_dict) or (None, None)."""
    if not name:
        return None, None
    canonical = _LOOKUP.get(name.strip().lower())
    if canonical:
        return canonical, DRUG_DATABASE[canonical]
    return None, None


def all_drug_names():
    return sorted(DRUG_DATABASE.keys())


def build_fallback_profile(drug_name, condition=None, review_stats=None):
    """
    Build a complete, non-blank profile for a drug that is present in the
    review dataset / recommendation model but has no hand-curated entry.
    Every field is populated (never null/blank) using what is actually known
    (name, condition, aggregated review data) plus an honest notice for the
    fields that require a licensed professional/official reference to state
    precisely — this avoids ever showing a blank drug report while never
    fabricating clinical specifics we can't verify.
    """
    consult_note = "Consult a licensed pharmacist, physician, or the official prescribing information for this specific detail."
    return {
        "generic_name": drug_name,
        "brand_names": [],
        "drug_class": "Prescription/OTC Medication" ,
        "description": f"{drug_name} is a medication used in the treatment of {condition or 'the associated condition'}. A full curated clinical profile for this specific drug is not yet available in IDPDR's knowledge base; the summary below is based on aggregated patient review data.",
        "uses": [condition] if condition else [],
        "dosage": {"note": consult_note},
        "side_effects": [consult_note],
        "contraindications": [consult_note],
        "drug_interactions": [consult_note],
        "food_interactions": [consult_note],
        "pregnancy": consult_note,
        "breastfeeding": consult_note,
        "kidney_warning": consult_note,
        "liver_warning": consult_note,
        "storage": "Store as directed on the package label, typically at room temperature away from moisture and heat.",
        "overdose": "In case of suspected overdose, contact emergency services or a poison control center immediately.",
        "missed_dose": "Follow the instructions on your prescription label, or ask your pharmacist or doctor.",
        "alternatives": [],
        "price_inr": "Consult pharmacist",
        "prescription_required": True,
        "manufacturer": "Various",
        "availability": "Consult local pharmacy",
        "condition": condition or "",
    }
