# Generated by Django 4.2.30 on 2026-07-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druginteractioncheck',
            options={'ordering': ['-created_at'], 'verbose_name': 'Drug Interaction Check'},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Disease Prediction'},
        ),
        migrations.AlterField(
            model_name='drugcomparison',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='druginteractioncheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drugreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saveddiagnosis',
            name='condition',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saveddiagnosis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Guest Patient', max_length=200)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=20)),
                ('symptoms', models.TextField()),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('recommended_drugs', models.JSONField(blank=True, default=list)),
                ('recommended_tests', models.JSONField(blank=True, default=list)),
                ('precautions', models.JSONField(blank=True, default=list)),
                ('lifestyle_recommendations', models.JSONField(blank=True, default=list)),
                ('doctor_notes', models.TextField(blank=True, default='This report was generated by an AI-assisted recommendation system and is intended for informational purposes only. It does not constitute a medical diagnosis. Please consult a licensed physician for confirmation and treatment.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='recommender.prediction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease Diagnosis Report',
                'ordering': ['-created_at'],
            },
        ),
    ]
