# Generated by Django 4.2.30 on 2026-07-06 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def rename_user_role_to_patient(apps, schema_editor):
    """Data migration: the 'user' role value is renamed to 'patient' for
    clarity (matches the new Patient/Admin terminology). No rows are
    deleted; this only updates the `role` string on existing profiles."""
    UserProfile = apps.get_model('recommender', 'UserProfile')
    UserProfile.objects.filter(role='user').update(role='patient')


def reverse_rename(apps, schema_editor):
    UserProfile = apps.get_model('recommender', 'UserProfile')
    UserProfile.objects.filter(role='patient').update(role='user')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommender', '0002_alter_druginteractioncheck_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow new patients to self-register')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Block non-admin logins while enabled')),
                ('site_name', models.CharField(default='IDPDR', max_length=100)),
                ('support_email', models.CharField(default='support@idpdr.ai', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('admin', 'Administrator')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('brand_names', models.CharField(blank=True, help_text='Comma-separated', max_length=300)),
                ('drug_class', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(blank=True, max_length=300)),
                ('side_effects', models.TextField(blank=True, help_text='Comma-separated')),
                ('contraindications', models.TextField(blank=True, help_text='Comma-separated')),
                ('price_inr', models.CharField(blank=True, max_length=100)),
                ('prescription_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drugs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Managed Drug',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Updated'), ('role_change', 'Role Changed'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('user_deleted', 'User Deleted'), ('drug_created', 'Drug Created'), ('drug_updated', 'Drug Updated'), ('drug_deleted', 'Drug Deleted'), ('settings_updated', 'Settings Updated')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(rename_user_role_to_patient, reverse_rename),
    ]
